---
# Secret needed to pull images from Quay.io Docker registry
apiVersion: v1
kind: Secret
metadata:
  name: ACMES-pull-secret
  namespace: "{{ .Values.namespace }}"
data:
  .dockerconfigjson: "{{ .Values.dockerconfigjson }}"
  type: kubernetes.io/dockerconfigjson
---
kind: Secret
apiVersion: v1
metadata:
  name: ACME-security-rollbar
  namespace: "{{ .Values.namespace }}"
data:
  rollbar-token: "{{ .Values.RollbarToken }}"
type: Opaque
